name: Create Release

on:
  workflow_run:
    workflows: "Build"
    types:
      - completed
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981 # FIXME: check when softprops makes a new release that fixes the node warning
        with:
          files: |
            ./*.so
            ./*.dll
            ./*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
